### PR TITLE
Setup for CocoaPods and SPM distribution

### PR DESCRIPTION
**Pull request by jkmassel**
Adds instructions on how to use the library, as well as the Podspec and Package.swift that make it work.

Doesn't yet publish the package to CocoaPods.

SwiftPM only allows packages to be distributed as ZIP files, so this PR adjusts that.

### CODE REVIEW

**Comment by jkmassel** [comment]
Ok, so weirdly enough 42fbf15 works, but it's...kinda gross.

For some reason the `sources` key seems to be ignored, but if I download the ZIP file manually and process it everything is fine? 

I'm not sure what I'm missing – I know the `sha1` is wrong, but I'd expect that to fail the build, not for `pod install` to just silently continue?

I think this approach proves the concept, but I might have to dig into CocoaPods internals to figure out the `source` issue

**Comment by mokagio** [comment]
> I'm not sure what I'm missing [...]
>
> I think this approach proves the concept, but I might have to dig into CocoaPods internals to figure out the source issue

That's [the same conclusion I got to](https://github.com/wordpress-mobile/WordPress-iOS/pull/20717/commits/a1b7531ab3fb92cff7dadd748700d2c3d4648e89#diff-05960bb2e77353597e92170859343bbb5bf7e6c29f3def8228ef758de6d372c6R42-R46) 😞 

I started looking into [`cocoapods-downloader`](https://github.com/CocoaPods/cocoapods-downloader) which is what CP use to download sources etc, but haven't found the point where it tries to download and unpack an `http:` source.

**Comment by Ecarrion** [comment]
Hi @jkmassel! 

How are things going? Is merging this PR still part of your plan?

I ask because we are soon going to include the framework inside the main WC app and it would be good to do it through a POD or SPM package. 

cc @wzieba

**Comment by jkmassel** [comment]
@Ecarrion – sorry about the wait – this is ready.

CocoaPods is still a bit of a mess (we can make it build fine if we reference the Git repo, but we can't push to a public Pod until we figure out why it doesn't properly support `xcframework` distribution). 

Fortunately, WCiOS seems to already heavily use SwiftPM, and that works fine. The release process is a little weird, but I've added it to `README.md`, so you can feel free to perform releases as needed, or I'm happy to help out with that.

Please try adding this repo to the project using SwiftPM, and choose the `0.1.0` release. It should work just fine, and if so, we can land this PR.

/cc @shiki

**Review by Ecarrion — APPROVED** [review]
@jkmassel the SPM version seems to work fine on the WCiOS app. Thanks!

Can I( or you?) release the latest trunk as a new version to do a more comprehensive test? 😁

**Comment by mokagio** [comment]
@jkmassel 

> CocoaPods is still a bit of a mess (we can make it build fine if we reference the Git repo, but we can't push to a public Pod until we figure out why it doesn't properly support xcframework distribution).

#51 should move us in the right direction

**Pull request merged**
